### PR TITLE
Updated code and fixed some bugs

### PR DESCRIPTION
**Pull request by Jacotsu**

### CODE REVIEW

**Comment by davethecipo** [comment]
Wow I didn't know someone apart from me actually used Polibeepsync! 

Since I'm no longer maintaining this code (not a student anymore), would you like me to transfer the repository ownership to you?

**Comment by Jacotsu** [comment]
> Wow I didn't know someone apart from me actually used Polibeepsync!
> 
> Since I'm no longer maintaining this code (not a student anymore), would you like me to transfer the repository ownership to you?

It would be appreciated, especially the ownership of the pypi package.

**Comment by davethecipo** [comment]
Regarding the github repo, you need to temporarly remove your fork so that I can initiate the transfer (see https://help.github.com/articles/about-repository-transfers/).

Regarding the pypi package, I need your username on pypi to add you as owner

**Comment by Jacotsu** [comment]
> Regarding the github repo, you need to temporarly remove your fork so that I can initiate the transfer (see https://help.github.com/articles/about-repository-transfers/).
> 
> Regarding the pypi package, I need your username on pypi to add you as owner

i've deleted my fork.
jacotsu is my pypi username

**Comment by davethecipo** [comment]
I sent you the request to transfer the repo ownership and added you as owner on pypi.

P.S: I forgot the name, but there is a script somewhere that does the job of polibeepsync via cli commands, it has nice code and actually works, since the author(s) found a way to interact with the site without web-scraping. I'm sure you can find it if you ask in Facebook Groups of Polimi students.

**Comment by Jacotsu** [comment]
> I sent you the request to transfer the repo ownership and added you as owner on pypi.
> 
> P.S: I forgot the name, but there is a script somewhere that does the job of polibeepsync via cli commands, it has nice code and actually works, since the author(s) found a way to interact with the site without web-scraping. I'm sure you can find it if you ask in Facebook Groups of Polimi students.

thanks.
I've never heard of the cli script, did they find a way to use the webdav interface?

**Comment by davethecipo** [comment]
I think so. I'm sorry that I can't help you more than this. Good luck!

**Pull request merged**
